/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartType: typeof import('./src/components/ChartType.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabPane1: typeof import('element-plus/es')['ElTabPane1']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
